### ISSUE TITLE
Motors run even with an expected distance equal to 0

### ISSUE THREAD

**Issue by cuillerj** [cuillerj/motorControl2342L#1]

**Comment by cuillerj** [comment]
it makes around a quater of turn

**Comment by rizthon** [comment]
Corrected this issue.
Still have a similar issue when we ask for a very small distance to cover (we only check afterwards that sufficient distance has been covered, is there a way to turn on an arduino pinout for a given time?)

**Comment by cuillerj** [comment]
I guess it is possible using timer3 without side effect

**Comment by rizthon** [comment]
??? What's that?

**Comment by cuillerj** [comment]
http://playground.arduino.cc/Code/Timer1
